# Generated by Django 4.2 on 2023-04-19 14:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PublishingHouse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('rating', models.IntegerField(default=5)),
            ],
            options={
                'db_table': 'publishing_house',
            },
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('author', models.CharField(max_length=100)),
                ('year', models.IntegerField()),
                ('price', models.CharField(max_length=10)),
                ('publishing_house', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='book.publishinghouse')),
            ],
            options={
                'db_table': 'book',
            },
        ),
    ]
